# Generated by Django 2.2.9 on 2020-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_auto_20200117_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ManyToManyField(blank=True, help_text='Select all the Company located in this Location.', to='catalog.Company')),
                ('plot', models.ManyToManyField(blank=True, help_text='Select all the Plot located in this Location.', to='catalog.Plot')),
                ('realtor', models.ManyToManyField(blank=True, help_text='Select all the Realtor located in this Location.', to='catalog.Realtor')),
            ],
        ),
    ]
