# Generated by Django 2.2.9 on 2020-04-05 05:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField(null=True)),
                ('about_town', ckeditor.fields.RichTextField(null=True)),
                ('town_pic', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('tytube_video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('town_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('is_published', models.BooleanField(default=True)),
                ('location', models.ManyToManyField(blank=True, help_text='Select The  Locations found in this Town', to='locations.Location')),
            ],
        ),
    ]
