# Generated by Django 2.2.9 on 2020-04-21 10:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('population', models.IntegerField(null=True)),
                ('about_town', ckeditor.fields.RichTextField(null=True)),
                ('town_pic', models.ImageField(null=True, upload_to='towns/%Y/%m/%d/')),
                ('town_pic1', models.ImageField(null=True, upload_to='towns/%Y/%m/%d/')),
                ('town_pic2', models.ImageField(null=True, upload_to='towns/%Y/%m/%d/')),
                ('county_flag_pic', models.ImageField(null=True, upload_to='countys_flags/%Y/%m/%d/')),
                ('tytube_video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('town_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ManyToManyField(blank=True, help_text='Select The  Locations found in this Town', to='locations.Location')),
            ],
        ),
    ]
