# Generated by Django 2.2.9 on 2020-01-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='town',
            name='company',
        ),
        migrations.RemoveField(
            model_name='town',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='town',
            name='realtor',
        ),
    ]
