# Generated by Django 2.2.9 on 2020-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='count_flag_pic',
            field=models.ImageField(null=True, upload_to='countys_flags/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='town',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
