# Generated by Django 2.2.9 on 2020-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200117_1437'),
        ('towns', '0002_auto_20200117_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Select The  Locations found in this Town', to='locations.Location'),
        ),
    ]
