# Generated by Django 2.2.9 on 2020-04-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0002_auto_20200417_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='count_flag_pic',
            new_name='county_flag_pic',
        ),
    ]
