# Generated by Django 2.2.9 on 2020-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_town_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
