# Generated by Django 2.2.9 on 2020-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0004_town_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='town_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
