# Generated by Django 2.2.9 on 2020-02-08 14:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0005_town_town_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='about_town',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='town',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
