# Generated by Django 2.2.9 on 2020-06-24 12:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='date_posted')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='Lesson_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail-photos/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usercreator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
