# Generated by Django 2.2.9 on 2020-06-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='video_name',
        ),
    ]
