# Generated by Django 2.2.9 on 2020-06-19 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_realtor',
        ),
        migrations.AddField(
            model_name='profile',
            name='accountname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountname', to=settings.AUTH_USER_MODEL),
        ),
    ]
