# Generated by Django 2.2.9 on 2020-06-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_remove_class_class_students'),
        ('users', '0003_auto_20200619_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='classname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Class'),
        ),
    ]
