# Generated by Django 2.2.9 on 2020-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='classname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
