# Generated by Django 2.2.9 on 2020-06-21 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='classname',
            new_name='user_class',
        ),
    ]
