# Generated by Django 2.2.9 on 2020-06-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200621_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='date_posted'),
        ),
    ]
