# Generated by Django 2.2.9 on 2020-06-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200621_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
