# Generated by Django 2.2.9 on 2020-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20200524_1410'),
        ('students', '0002_student_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='interested_students', to='subjects.Subject'),
        ),
    ]
