# Generated by Django 2.2.9 on 2020-06-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classname',
        ),
    ]
