# Generated by Django 2.2.9 on 2020-06-07 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200607_1246'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0005_remove_student_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classname', to='classes.Class'),
        ),
        migrations.AddField(
            model_name='student',
            name='useraccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentuseraccount', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdby', to=settings.AUTH_USER_MODEL),
        ),
    ]
