# Generated by Django 2.2.9 on 2020-06-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200607_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classname',
        ),
    ]
