# Generated by Django 2.2.9 on 2020-06-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Class'),
        ),
    ]
