# Generated by Django 2.2.9 on 2020-05-21 12:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, null=True, unique_for_date='date_posted')),
                ('class_monitor', models.CharField(blank=True, max_length=200, null=True)),
                ('class_prefect', models.CharField(blank=True, max_length=200, null=True)),
                ('about_class', ckeditor.fields.RichTextField(null=True)),
                ('class_pic', models.ImageField(null=True, upload_to='class_pics/%Y/%m/%d/')),
                ('class_video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('class_video', models.FileField(blank=True, null=True, upload_to='class_videos/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('class_name', models.ForeignKey(help_text='The class name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Class_name')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_teacher', to='teachers.Teacher')),
                ('computer_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='computer_teacher', to='teachers.Teacher')),
                ('english_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='english_teacher', to='teachers.Teacher')),
                ('home_science_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_science_teacher', to='teachers.Teacher')),
                ('kiswahili_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kiswahili_teacher', to='teachers.Teacher')),
                ('maths_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maths_teacher', to='teachers.Teacher')),
                ('music_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='music_teacher', to='teachers.Teacher')),
                ('p_e_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_e_teacher', to='teachers.Teacher')),
                ('social_studies_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='social_studies_teacher', to='teachers.Teacher')),
            ],
        ),
    ]
