# Generated by Django 2.2.9 on 2020-05-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200521_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_pic',
            field=models.ImageField(blank=True, null=True, upload_to='class_pics/%Y/%m/%d/'),
        ),
    ]
