# Generated by Django 2.2.9 on 2020-05-22 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colors', '0002_bg_color_2_bg_color_3'),
        ('classes', '0004_auto_20200522_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='bg_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color'),
        ),
        migrations.AddField(
            model_name='class',
            name='bg_color_2',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color_2'),
        ),
        migrations.AddField(
            model_name='class',
            name='bg_color_3',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color_3'),
        ),
        migrations.AddField(
            model_name='class',
            name='border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Border_color'),
        ),
        migrations.AddField(
            model_name='class',
            name='color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Color'),
        ),
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='footer_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Footer_color'),
        ),
        migrations.AddField(
            model_name='class',
            name='hover_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_color'),
        ),
        migrations.AddField(
            model_name='class',
            name='hover_text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_text_color'),
        ),
        migrations.AddField(
            model_name='class',
            name='text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Text_color'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='computer_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='computer_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='english_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='english_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='home_science_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_science_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='kiswahili_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kiswahili_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='maths_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maths_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='music_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='music_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='p_e_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='p_e_teacher', to='teachers.Teacher'),
        ),
        migrations.AlterField(
            model_name='class',
            name='social_studies_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='social_studies_teacher', to='teachers.Teacher'),
        ),
    ]
