# Generated by Django 2.2.9 on 2020-05-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_notice_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice_board',
        ),
    ]
