# Generated by Django 2.2.9 on 2020-06-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_delete_notice_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
    ]
