# Generated by Django 2.2.9 on 2020-06-07 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0009_auto_20200602_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='class_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
