# Generated by Django 2.2.9 on 2020-06-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_class_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='students',
            new_name='class_students',
        ),
    ]
