# Generated by Django 2.2.9 on 2020-06-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200607_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_students',
        ),
    ]
