# Generated by Django 2.2.9 on 2020-06-18 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0012_remove_class_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_students',
            field=models.ManyToManyField(blank=True, related_name='class_joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
