# Generated by Django 2.2.9 on 2020-06-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_class_class_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_students',
        ),
    ]
