# Generated by Django 2.2.9 on 2020-06-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_account_classname'),
        ('classes', '0014_remove_class_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='account',
            field=models.ManyToManyField(blank=True, help_text='pick authorized personel to view class', to='users.Account'),
        ),
    ]
