# Generated by Django 2.2.9 on 2020-06-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_auto_20200621_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classx',
            old_name='account',
            new_name='accounts',
        ),
    ]
