# Generated by Django 2.2.9 on 2020-07-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_class_name_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='about_class',
        ),
        migrations.RemoveField(
            model_name='class',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='bg_color_2',
        ),
        migrations.RemoveField(
            model_name='class',
            name='bg_color_3',
        ),
        migrations.RemoveField(
            model_name='class',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_pic',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_video',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_video_link',
        ),
        migrations.RemoveField(
            model_name='class',
            name='color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='footer_color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='hover_color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='hover_text_color',
        ),
        migrations.RemoveField(
            model_name='class',
            name='text_color',
        ),
    ]
