# Generated by Django 2.2.9 on 2020-05-24 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0008_delete_notice_board'),
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice_board',
            new_name='Notice',
        ),
    ]
