# Generated by Django 2.2.9 on 2020-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_videolisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolisting',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
