# Generated by Django 2.2.9 on 2020-03-18 18:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_auto_20200318_1620'),
        ('locations', '0005_auto_20200213_0937'),
        ('companys', '0018_auto_20200318_1802'),
        ('towns', '0006_auto_20200208_1745'),
        ('listings', '0002_bg_color_border_color_color_development_footer_color_hover_border_color_hover_color_hover_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bg_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Bg_color'),
        ),
        migrations.AddField(
            model_name='listing',
            name='border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Border_color'),
        ),
        migrations.AddField(
            model_name='listing',
            name='business',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business'),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Color'),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='development',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Development'),
        ),
        migrations.AddField(
            model_name='listing',
            name='electricity',
            field=models.CharField(help_text='distance from the closest transformer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='hover_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Hover_color'),
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(help_text='add a location closet to the plot in the picked town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='neighbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Neighbor'),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plan',
            field=models.ForeignKey(help_text='mode of payment required', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Payment_plan'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='plot_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Plot_size'),
        ),
        migrations.AddField(
            model_name='listing',
            name='plot_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Plot_status'),
        ),
        migrations.AddField(
            model_name='listing',
            name='plot_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Plot_type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='population',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Population'),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Broker'),
        ),
        migrations.AddField(
            model_name='listing',
            name='roads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Road'),
        ),
        migrations.AddField(
            model_name='listing',
            name='text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listings.Text_color'),
        ),
        migrations.AddField(
            model_name='listing',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='towns.Town'),
        ),
        migrations.AddField(
            model_name='listing',
            name='water',
            field=models.CharField(help_text='the distance from water pipe or source', max_length=100, null=True),
        ),
    ]
