# Generated by Django 2.2.9 on 2020-03-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200318_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='realtor',
            new_name='broker',
        ),
    ]
