# Generated by Django 2.2.9 on 2020-04-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_videolisting_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolisting',
            old_name='plot',
            new_name='listing',
        ),
    ]
