# Generated by Django 2.2.9 on 2020-04-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200319_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='plot_video',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
