# Generated by Django 2.2.9 on 2020-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_plot_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pytube_video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='plot_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
