# Generated by Django 2.2.9 on 2020-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select this church members', to='members.Member'),
        ),
    ]
