# Generated by Django 2.2.9 on 2020-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('churches', '0002_church_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church_member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='church_member',
            name='last_name',
        ),
        migrations.AddField(
            model_name='church_member',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Select this church members', to='members.Member'),
        ),
    ]
