# Generated by Django 2.2.9 on 2020-03-28 11:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_auto_20200327_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_theme',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, help_text='150 words max', max_length=4000, null=True),
        ),
    ]
