# Generated by Django 2.2.9 on 2020-03-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_auto_20200328_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='first_service_leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ministering_choir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='second_service_leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='todays_speaker_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='todays_speaker_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
