# Generated by Django 2.2.9 on 2020-04-22 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_auto_20200422_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='churchmember',
            field=models.ManyToManyField(blank=True, help_text='Select this church members', to='members.Member'),
        ),
        migrations.AlterField(
            model_name='church',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
