# Generated by Django 2.2.9 on 2020-03-28 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0004_auto_20200328_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='Service_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
