# Generated by Django 2.2.9 on 2020-04-22 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('churches', '0005_auto_20200422_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church_member',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='church_member',
            name='members',
        ),
        migrations.AddField(
            model_name='church_member',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
