# Generated by Django 2.2.9 on 2020-03-29 07:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0005_schedule_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hymn',
            name='church',
        ),
        migrations.AddField(
            model_name='hymn',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hymn_of_the_week',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='church_choir',
            name='choir_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Church_member'),
        ),
        migrations.AlterField(
            model_name='church_choir',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Church'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='hymn',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='hymn_of_the_week',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Church'),
        ),
        migrations.AlterField(
            model_name='hymn_of_the_week',
            name='hymn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Hymn'),
        ),
    ]
