# Generated by Django 2.2.9 on 2020-03-29 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0008_auto_20200329_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
