# Generated by Django 2.2.9 on 2020-03-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0011_auto_20200329_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_theme',
            name='video',
        ),
    ]
