# Generated by Django 2.2.9 on 2020-03-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0012_remove_weekly_theme_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Church'),
        ),
        migrations.AddField(
            model_name='video',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='churches.Church'),
        ),
    ]
