# Generated by Django 2.2.9 on 2020-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0013_auto_20200329_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
