# Generated by Django 2.2.9 on 2020-06-28 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bgimg', models.ImageField(blank=True, null=True, upload_to='bgimg/')),
                ('bgimg_1', models.ImageField(blank=True, null=True, upload_to='bgimg/')),
                ('bgimg_2', models.ImageField(blank=True, null=True, upload_to='bgimg/')),
                ('bgimg_3', models.ImageField(blank=True, null=True, upload_to='bgimg/')),
                ('reload', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
