# Generated by Django 2.2.9 on 2020-05-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='date_posted')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ImageField(blank=True, default='avatar.jpg', upload_to='profiles/%Y/%m/%d/')),
                ('st_video_link', models.CharField(blank=True, help_text='teacher external video link', max_length=1000, null=True)),
                ('teacher_video', models.FileField(blank=True, help_text='teacher internal video link', null=True, upload_to='videos/')),
                ('about_teacher', models.TextField(blank=True, help_text='Enter a brief description of the Realtor.', max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, help_text='add your languages', to='teachers.Language')),
                ('skills', models.ManyToManyField(blank=True, help_text='add your skills', to='teachers.Skill')),
                ('subjects', models.ManyToManyField(blank=True, help_text='Select the subjects which this teacher teach', to='subjects.Subject')),
            ],
        ),
    ]
