# Generated by Django 2.2.9 on 2020-06-07 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0003_remove_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='useraccount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacheruseraccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
