# Generated by Django 2.2.9 on 2020-07-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
