# Generated by Django 2.2.9 on 2020-06-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='Sub_strand',
        ),
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='image',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='learning_area',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='strand',
            name='learning_a',
        ),
        migrations.RemoveField(
            model_name='sub_strand',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='text',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Learning_area',
        ),
        migrations.DeleteModel(
            name='Strand',
        ),
        migrations.DeleteModel(
            name='Sub_strand',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
