# Generated by Django 2.2.9 on 2020-04-05 05:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('towns', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Border_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Business_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hover_border_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hover_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hover_text_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(max_length=100, null=True)),
                ('business_slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('f_title1', models.CharField(blank=True, help_text='feature title 1', max_length=200, null=True)),
                ('features_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('f_title2', models.CharField(blank=True, help_text='feature title 2', max_length=200, null=True)),
                ('features_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('f_title3', models.CharField(blank=True, help_text='feature title 3', max_length=200, null=True)),
                ('features_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('f_title4', models.CharField(blank=True, help_text='feature title 4', max_length=200, null=True)),
                ('features_4', models.CharField(blank=True, max_length=1000, null=True)),
                ('business_pic', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('logo', models.ImageField(blank=True, default='logo.png', null=True, upload_to='logos/%Y/%m/%d/')),
                ('about_pic', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('service_pic', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('bgimg_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('bgimg_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('bgimg_3', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('about_business', ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True)),
                ('services', ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True)),
                ('bytube_video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('business_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('email_1', models.CharField(blank=True, max_length=100, null=True)),
                ('email_2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('company_created_on', models.DateTimeField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_thika', models.BooleanField(default=False)),
                ('is_ruiru', models.BooleanField(default=False)),
                ('is_maimahiu', models.BooleanField(default=False)),
                ('is_kiambu', models.BooleanField(default=False)),
                ('is_gatundu', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('bg_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Bg_color')),
                ('border_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Border_color')),
                ('business_type', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business_type')),
                ('color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Color')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('footer_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Footer_color')),
                ('hover_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Hover_color')),
                ('location', models.ForeignKey(blank=True, help_text='Select The exact locations where this Company  is found in the choosen Town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location')),
                ('text_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Text_color')),
                ('town', models.ForeignKey(blank=True, help_text='Select The exact towns this company is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='towns.Town')),
            ],
        ),
    ]
