# Generated by Django 2.2.9 on 2020-04-08 03:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='about_business',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='services',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', null=True),
        ),
    ]
