# Generated by Django 2.2.9 on 2020-03-18 12:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0006_auto_20200208_1745'),
        ('locations', '0005_auto_20200213_0937'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bg_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Border_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hover_border_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hover_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hover_text_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text_color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='Instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='about_business',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='about_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='contact_person',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='email_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='email_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Select The exact locations where this Company  is found in the choosen Town', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', upload_to='logos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='service_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='town',
            field=models.ManyToManyField(blank=True, help_text='Select The exact towns this company is located.', to='towns.Town'),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='bg_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Bg_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Border_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Color'),
        ),
        migrations.AddField(
            model_name='business',
            name='footer_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Footer_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='hover_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Hover_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Text_color'),
        ),
    ]
