# Generated by Django 2.2.9 on 2020-04-11 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20200408_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title1', models.CharField(blank=True, help_text='feature title 1', max_length=200, null=True)),
                ('features_1', models.CharField(blank=True, max_length=1000, null=True)),
                ('f_title2', models.CharField(blank=True, help_text='feature title 2', max_length=200, null=True)),
                ('features_2', models.CharField(blank=True, max_length=1000, null=True)),
                ('f_title3', models.CharField(blank=True, help_text='feature title 3', max_length=200, null=True)),
                ('features_3', models.CharField(blank=True, max_length=1000, null=True)),
                ('f_title4', models.CharField(blank=True, help_text='feature title 4', max_length=200, null=True)),
                ('business_name', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Bimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_pic', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('logo', models.ImageField(blank=True, default='logo.png', null=True, upload_to='logos/%Y/%m/%d/')),
                ('about_pic', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('service_pic', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('bgimg_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('bgimg_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('bgimg_3', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('business_name', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Bcontacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_1', models.CharField(blank=True, max_length=100, null=True)),
                ('email_2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_3', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business')),
            ],
        ),
    ]
