# Generated by Django 2.2.9 on 2020-04-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20200426_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bgimg_1',
            new_name='bgimg1',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bgimg_2',
            new_name='bgimg2',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='bgimg_3',
            new_name='bgimg3',
        ),
    ]
