# Generated by Django 2.2.9 on 2020-03-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_auto_20200318_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='business',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email_1',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email_2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='business',
            name='footer_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='hover_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_1',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='service_pic',
        ),
        migrations.RemoveField(
            model_name='business',
            name='services',
        ),
        migrations.RemoveField(
            model_name='business',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='town',
        ),
        migrations.RemoveField(
            model_name='business',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
    ]
