# Generated by Django 2.2.9 on 2020-04-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_bcontacts_bimages_feature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bcontacts',
            new_name='Bcontact',
        ),
        migrations.RenameModel(
            old_name='Bimages',
            new_name='Bimage',
        ),
    ]
