# Generated by Django 2.2.9 on 2020-03-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_auto_20200318_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='about_business',
        ),
        migrations.RemoveField(
            model_name='business',
            name='about_pic',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_pic',
        ),
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
    ]
