# Generated by Django 2.2.9 on 2020-04-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0004_auto_20200411_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='features_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
