# Generated by Django 2.2.9 on 2020-03-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0006_auto_20200318_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bg_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Bg_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Border_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Color'),
        ),
        migrations.AddField(
            model_name='business',
            name='footer_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Footer_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='hover_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Hover_color'),
        ),
        migrations.AddField(
            model_name='business',
            name='text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Text_color'),
        ),
    ]
