# Generated by Django 2.2.9 on 2020-04-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0006_auto_20200418_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cp_email_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cp_img',
            field=models.ImageField(blank=True, null=True, upload_to='contact_person/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='cp_phone_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cp_phone_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
