# Generated by Django 2.2.9 on 2020-03-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0006_auto_20200208_1745'),
        ('locations', '0005_auto_20200213_0937'),
        ('companys', '0007_auto_20200318_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Select The exact locations where this Company  is found in the choosen Town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='business',
            name='town',
            field=models.ForeignKey(blank=True, help_text='Select The exact towns this company is located.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='towns.Town'),
        ),
    ]
