# Generated by Django 2.2.9 on 2020-03-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0009_auto_20200318_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='about_business',
        ),
        migrations.RemoveField(
            model_name='business',
            name='services',
        ),
    ]
