# Generated by Django 2.2.9 on 2020-03-18 14:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0010_auto_20200318_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='about_pic',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_pic',
        ),
        migrations.RemoveField(
            model_name='business',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='business',
            name='service_pic',
        ),
        migrations.AddField(
            model_name='business',
            name='about_business',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True),
        ),
    ]
