# Generated by Django 2.2.9 on 2020-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0011_auto_20200318_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
