# Generated by Django 2.2.9 on 2020-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0012_business_business_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(default='panorama.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
