# Generated by Django 2.2.9 on 2020-03-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0013_auto_20200318_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='about_pic',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', upload_to='logos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='business',
            name='service_pic',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
