# Generated by Django 2.2.9 on 2020-03-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0014_auto_20200318_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='about_pic',
            field=models.ImageField(default='panorama.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='panorama.jpg'),
        ),
        migrations.AlterField(
            model_name='business',
            name='service_pic',
            field=models.ImageField(default='panorama.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
