# Generated by Django 2.2.9 on 2020-03-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0018_auto_20200318_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='features_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='features_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='features_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='features_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
