# Generated by Django 2.2.9 on 2020-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0019_auto_20200320_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='f_title1',
            field=models.CharField(blank=True, help_text='feature title 1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='f_title2',
            field=models.CharField(blank=True, help_text='feature title 2', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='f_title3',
            field=models.CharField(blank=True, help_text='feature title 3', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='f_title4',
            field=models.CharField(blank=True, help_text='feature title 4', max_length=200, null=True),
        ),
    ]
