# Generated by Django 2.2.9 on 2020-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0021_auto_20200320_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_gatundu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_kiambu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_maimahiu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_ruiru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='is_thika',
            field=models.BooleanField(default=False),
        ),
    ]
