# Generated by Django 2.2.9 on 2020-03-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0022_auto_20200321_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_posted',
            field=models.DateTimeField(null=True),
        ),
    ]
