# Generated by Django 2.2.9 on 2020-04-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0025_auto_20200331_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='phone_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
