# Generated by Django 2.2.9 on 2020-04-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0026_business_phone_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='bimg_1',
            new_name='bgimg_1',
        ),
    ]
