# Generated by Django 2.2.9 on 2020-04-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0027_auto_20200401_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_video',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
