# Generated by Django 2.2.9 on 2020-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0028_business_business_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='bytube_video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
