# Generated by Django 2.2.9 on 2020-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0029_auto_20200402_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='bgimg_3',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
