# Generated by Django 2.2.9 on 2020-06-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_auto_20200602_2111'),
        ('exercises', '0002_exercise_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='classname',
        ),
        migrations.AddField(
            model_name='exercise',
            name='classname',
            field=models.ManyToManyField(help_text='Pick all classes you would like to send this exercise to NOTE you can choose one', to='classes.Class'),
        ),
    ]
