# Generated by Django 2.2.9 on 2020-06-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_auto_20200603_0128'),
        ('subjects', '0009_auto_20200603_0128'),
        ('exercises', '0003_auto_20200602_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Topic'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='classname',
            field=models.ManyToManyField(help_text='Pick all classes you would like to send this exercise to; NOTE you can choose one', to='classes.Class'),
        ),
    ]
