# Generated by Django 2.2.9 on 2020-06-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200603_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
