# Generated by Django 2.2.9 on 2020-06-03 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0005_auto_20200603_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
