# Generated by Django 2.2.9 on 2020-06-07 16:47

from django.db import migrations
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_auto_20200604_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='questions',
            field=django_ckeditor_5.fields.CKEditor5Field(default=django.utils.timezone.now, verbose_name='Question'),
            preserve_default=False,
        ),
    ]
