# Generated by Django 2.2.9 on 2020-06-07 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20200607_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='questions',
            field=ckeditor.fields.RichTextField(null=True, unique=True),
        ),
    ]
