# Generated by Django 2.2.9 on 2020-06-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20200607_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='diagrams/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='file_name',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
