# Generated by Django 2.2.9 on 2020-06-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200607_1246'),
        ('exercises', '0013_exercise_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='topic',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answering', to='students.Student'),
        ),
    ]
