# Generated by Django 2.2.9 on 2020-06-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200625_0954'),
        ('exercises', '0015_auto_20200619_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video'),
        ),
    ]
