# Generated by Django 2.2.9 on 2020-07-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_answer_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='file_name',
        ),
        migrations.AddField(
            model_name='answer',
            name='upload',
            field=models.FileField(blank=True, help_text='upload your answer doc here', null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
