# Generated by Django 2.2.9 on 2020-07-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_auto_20200706_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video'),
        ),
    ]
