# Generated by Django 2.2.9 on 2020-07-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_auto_20200706_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='diagram',
        ),
    ]
