# Generated by Django 2.1.3 on 2019-12-24 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular plot in the system', primary_key=True, serialize=False)),
                ('plot_number', models.CharField(blank=True, max_length=200, null=True)),
                ('next_payment_due_when', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('s', 'Sold'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved'), ('m', 'Maintenance')], default='a', help_text='plot availability', max_length=1)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Plot')),
            ],
            options={
                'ordering': ['next_payment_due_when'],
                'permissions': (('can_mark_paid', 'Set plot as paid'),),
            },
        ),
    ]
