# Generated by Django 2.1.3 on 2019-12-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191224_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='town',
        ),
        migrations.AlterField(
            model_name='plotinstance',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
