# Generated by Django 2.1.3 on 2019-12-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191224_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='Instagram',
            new_name='instagram',
        ),
    ]
