# Generated by Django 2.2.9 on 2020-01-17 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20200117_1437'),
        ('towns', '0002_auto_20200117_1437'),
        ('catalog', '0008_auto_20200117_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Select The exact locations where this Company  is found in the choosen Town', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='town',
            field=models.ManyToManyField(blank=True, help_text='Select The exact towns this company is located.', to='towns.Town'),
        ),
        migrations.AddField(
            model_name='plot',
            name='location',
            field=models.ForeignKey(help_text='add a location closet to the plot in the picked town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='plot',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='towns.Town'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Select The  Locations where this realtor  is found in the choosen Town', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='town',
            field=models.ManyToManyField(blank=True, help_text='Select the towns where this realtor is found', to='towns.Town'),
        ),
    ]
