# Generated by Django 2.2.9 on 2020-01-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200117_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
