# Generated by Django 2.2.9 on 2020-01-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200117_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/%Y/%m/%d/'),
        ),
    ]
