# Generated by Django 2.2.9 on 2020-01-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', upload_to='logos/%Y/%m/%d/'),
        ),
    ]
