# Generated by Django 2.2.9 on 2020-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200118_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='profile',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
