# Generated by Django 2.2.9 on 2020-01-22 09:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_realtor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
