# Generated by Django 2.2.9 on 2020-01-22 09:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200122_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=ckeditor.fields.RichTextField(max_length=1500, null=True),
        ),
    ]
