# Generated by Django 2.2.9 on 2020-01-22 09:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200122_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='about_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='about_company',
            field=ckeditor.fields.RichTextField(help_text='Max 200 words', max_length=1500, null=True),
        ),
    ]
