# Generated by Django 2.2.9 on 2020-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200201_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
