# Generated by Django 2.2.9 on 2020-02-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200202_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='realtor_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
