# Generated by Django 2.2.9 on 2020-02-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200209_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_created_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
