# Generated by Django 2.2.9 on 2020-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_company_company_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_slogan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
