# Generated by Django 2.2.9 on 2020-04-21 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('towns', '0001_initial'),
        ('companys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colors', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.ImageField(blank=True, default='avatar.jpg', upload_to='profiles/%Y/%m/%d/')),
                ('rytube_video_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('realtor_video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('about_realtor', models.TextField(blank=True, help_text='Enter a brief description of the Realtor.', max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('bg_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color')),
                ('border_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Border_color')),
                ('business', models.ForeignKey(blank=True, help_text='Select The Company this realtor belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business')),
                ('color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Color')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('footer_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Footer_color')),
                ('hover_border_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_border_color')),
                ('hover_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_color')),
                ('hover_text_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_text_color')),
                ('location', models.ForeignKey(blank=True, help_text='Select The  Locations where this realtor  is found in the choosen Town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location')),
                ('text_color', models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Text_color')),
                ('town', models.ForeignKey(blank=True, help_text='Select the towns where this realtor is found', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='towns.Town')),
            ],
        ),
    ]
