# Generated by Django 2.2.9 on 2020-03-17 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200213_0937'),
        ('towns', '0006_auto_20200208_1745'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['last_name', 'first_name', 'phone']},
        ),
        migrations.AddField(
            model_name='broker',
            name='about_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='about_realtor',
            field=models.TextField(default=django.utils.timezone.now, help_text='Enter a brief description of the Realtor.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='advert_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='Select The  Locations where this realtor  is found in the choosen Town', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='broker',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='profile',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='statement',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='town',
            field=models.ManyToManyField(blank=True, help_text='Select the towns where this realtor is found', to='towns.Town'),
        ),
        migrations.AddField(
            model_name='broker',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
