# Generated by Django 2.2.9 on 2020-04-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='bg_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Border_color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='footer_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Footer_color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='hover_border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_border_color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='hover_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='hover_text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_text_color'),
        ),
        migrations.AddField(
            model_name='broker',
            name='text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Text_color'),
        ),
    ]
