# Generated by Django 2.2.9 on 2020-03-18 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20200317_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={},
        ),
        migrations.RemoveField(
            model_name='broker',
            name='about_pic',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='about_realtor',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='advert_pic',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='location',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='town',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='website',
        ),
    ]
