# Generated by Django 2.2.9 on 2020-03-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200213_0937'),
        ('towns', '0006_auto_20200208_1745'),
        ('realtors', '0003_auto_20200318_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='about_realtor',
            field=models.TextField(blank=True, help_text='Enter a brief description of the Realtor.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Select The  Locations where this realtor  is found in the choosen Town', null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='broker',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='profile',
            field=models.ImageField(blank=True, default='avatar.jpg', upload_to='profiles/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='town',
            field=models.ForeignKey(blank=True, help_text='Select the towns where this realtor is found', null=True, on_delete=django.db.models.deletion.CASCADE, to='towns.Town'),
        ),
        migrations.AddField(
            model_name='broker',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
