# Generated by Django 2.2.9 on 2020-03-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0002_auto_20200318_1536'),
        ('realtors', '0004_auto_20200318_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Select The Company this realtor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='companys.Business'),
        ),
    ]
