# Generated by Django 2.2.9 on 2020-03-18 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0005_broker_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Select The Company this realtor belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companys.Business'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='broker',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Select The  Locations where this realtor  is found in the choosen Town', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='town',
            field=models.ForeignKey(blank=True, help_text='Select the towns where this realtor is found', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='towns.Town'),
        ),
    ]
