# Generated by Django 2.2.9 on 2020-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_auto_20200318_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
