# Generated by Django 2.2.9 on 2020-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0007_broker_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='realtor_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='broker',
            name='rytube_video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
