# Generated by Django 2.2.9 on 2020-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20200521_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_level',
            field=models.CharField(help_text='which class is this subject for for e.g class 7 or class 2', max_length=100, null=True),
        ),
    ]
