# Generated by Django 2.2.9 on 2020-05-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_bg_color_2_bg_color_3'),
        ('subjects', '0003_subject_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hover_border_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_border_color'),
        ),
    ]
