# Generated by Django 2.2.9 on 2020-05-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subject_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='bg_color_2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='bg_color_3',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='footer_color',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hover_border_color',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hover_color',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hover_text_color',
        ),
    ]
