# Generated by Django 2.2.9 on 2020-05-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_text_color_2_text_color_3'),
        ('subjects', '0006_auto_20200523_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_teacher',
        ),
        migrations.AddField(
            model_name='subject',
            name='bg_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color'),
        ),
        migrations.AddField(
            model_name='subject',
            name='bg_color_2',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color_2'),
        ),
        migrations.AddField(
            model_name='subject',
            name='bg_color_3',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Bg_color_3'),
        ),
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Color'),
        ),
        migrations.AddField(
            model_name='subject',
            name='footer_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Footer_color'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hover_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_color'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hover_text_color',
            field=models.ForeignKey(blank=True, help_text='optional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.Hover_text_color'),
        ),
    ]
