# Generated by Django 2.2.9 on 2020-05-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_delete_notice_board'),
        ('subjects', '0007_auto_20200524_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_level',
        ),
        migrations.AddField(
            model_name='subject',
            name='specific_class',
            field=models.ForeignKey(blank=True, help_text='eg class 7 or class 7 North', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Class'),
        ),
    ]
