# Generated by Django 2.2.9 on 2020-01-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='plot_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='realtor_name',
        ),
    ]
