# Generated by Django 2.2.9 on 2020-02-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_pic',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
