# Generated by Django 2.2.9 on 2020-02-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_location_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_pic',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
