# Generated by Django 2.2.9 on 2020-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20200213_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='location',
            name='lytube_video_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
