# Generated by Django 2.2.9 on 2020-05-23 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20200523_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0002_auto_20200522_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram', models.ImageField(blank=True, null=True, upload_to='diagrams/%Y/%m/%d/')),
                ('question', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mvp', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ex_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Lesson')),
                ('ex_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_student', to=settings.AUTH_USER_MODEL)),
                ('ex_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject')),
                ('ex_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_teacher', to=settings.AUTH_USER_MODEL)),
                ('ex_topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Topic')),
            ],
        ),
    ]
