# Generated by Django 2.2.9 on 2020-05-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='ex_student',
        ),
    ]
