# Generated by Django 2.2.9 on 2020-05-23 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0004_remove_exercise_ex_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('excercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Exercise')),
                ('teacher_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_reply', to='lessons.Exercise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('excercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Exercise')),
                ('student_reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reply', to='lessons.Exercise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
