# Generated by Django 2.2.9 on 2020-05-23 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_student_answer_teacher_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_answer',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='teacher_answer',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='student_answer',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='student_answer',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='student_answer',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teacher_answer',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='teacher_answer',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='teacher_answer',
            old_name='user',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='student_answer',
            name='student_reply',
        ),
        migrations.RemoveField(
            model_name='teacher_answer',
            name='teacher_reply',
        ),
        migrations.AddField(
            model_name='student_answer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student_answer',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher_answer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher_answer',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
