# Generated by Django 2.2.9 on 2020-05-23 18:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20200523_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='answer',
            field=ckeditor.fields.RichTextField(blank=True, help_text='create answers for the exercises you created here', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_exercise',
            field=ckeditor.fields.RichTextField(blank=True, help_text='create exercises for this lesson', null=True),
        ),
    ]
