# Generated by Django 2.2.9 on 2020-05-25 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('subjects', '0007_auto_20200524_1410'),
        ('lessons', '0010_auto_20200525_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_doing_exercise',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='takenexercise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_exercisezes', to='lessons.Student_doing_exercise'),
        ),
        migrations.AddField(
            model_name='student_doing_exercise',
            name='exercises',
            field=models.ManyToManyField(through='lessons.TakenExercise', to='lessons.Exercise'),
        ),
        migrations.AddField(
            model_name='student_doing_exercise',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='subjects.Subject'),
        ),
    ]
