# Generated by Django 2.2.9 on 2020-05-25 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_delete_notice_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0007_auto_20200524_1410'),
        ('lessons', '0011_auto_20200525_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram', models.ImageField(blank=True, null=True, upload_to='diagrams/%Y/%m/%d/')),
                ('question', models.CharField(max_length=100, null=True)),
                ('option1', models.CharField(max_length=100, null=True)),
                ('option2', models.CharField(max_length=100, null=True)),
                ('option3', models.CharField(max_length=100, null=True)),
                ('option4', models.CharField(max_length=100, null=True)),
                ('corrans', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='Lesson_exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(max_length=250, null=True, unique_for_date='date_posted')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mvp', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ex_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='ex_lesson',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='ex_subject',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='ex_teacher',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='ex_topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='excercise',
        ),
        migrations.RemoveField(
            model_name='student_doing_exercise',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='student_doing_exercise',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='student_doing_exercise',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='takenexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='takenexercise',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher_answer',
            name='ex_lesson',
        ),
        migrations.RemoveField(
            model_name='teacher_answer',
            name='ex_subject',
        ),
        migrations.RemoveField(
            model_name='teacher_answer',
            name='ex_topic',
        ),
        migrations.RemoveField(
            model_name='teacher_answer',
            name='excercise',
        ),
        migrations.RemoveField(
            model_name='teacher_answer',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ans_pic',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ans_video',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ans_video_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ex_pic',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ex_video',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='ex_video_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_exercise',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Student_doing_exercise',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='TakenExercise',
        ),
        migrations.DeleteModel(
            name='Teacher_answer',
        ),
        migrations.AddField(
            model_name='lesson_exercise',
            name='ex_lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson_exercise',
            name='ex_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.Subject'),
        ),
        migrations.AddField(
            model_name='lesson_exercise',
            name='ex_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ex_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson_exercise',
            name='ex_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.Topic'),
        ),
        migrations.AddField(
            model_name='exercise_question',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='lessons.Lesson_exercise'),
        ),
    ]
