# Generated by Django 2.2.9 on 2020-05-25 09:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20200525_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_question',
            name='Explanation',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
