# Generated by Django 2.2.9 on 2020-05-25 09:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_exercise_question_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_question',
            name='Explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
