# Generated by Django 2.2.9 on 2020-05-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_auto_20200525_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_question',
            name='corrans',
            field=models.TextField(null=True),
        ),
    ]
