# Generated by Django 2.2.9 on 2020-05-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_delete_notice_board'),
        ('lessons', '0017_auto_20200527_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_question',
            name='ex_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
    ]
