# Generated by Django 2.2.9 on 2020-06-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_exercise_question_ex_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Sub_strand', 'verbose_name_plural': 'Sub_strands'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['date_posted'], 'verbose_name': 'Strand', 'verbose_name_plural': 'Strands'},
        ),
    ]
