# Generated by Django 2.2.9 on 2020-06-08 15:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_auto_20200603_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, help_text='input specific learning outcomes, val-ues, pcl, & core competence', null=True),
        ),
    ]
