# Generated by Django 2.2.9 on 2020-06-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200625_0954'),
        ('lessons', '0020_auto_20200608_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_video_link',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_video',
            field=models.ManyToManyField(blank=True, help_text='pick videos linked to this particular lesson', to='videos.Video'),
        ),
    ]
