# Generated by Django 2.2.9 on 2020-06-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200625_0954'),
        ('lessons', '0021_auto_20200625_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_video',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='videos.Video'),
        ),
    ]
